### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by Baccata**
* Change default generated folder to `smithy4s-quickstart`
* Unify SBT / Mill templates to avoid having to modified the generated Scala/Smithy code twice when making amendments 
* Modify the spec to contain a GET request at the `/hello/{name} path `
* Modify the spec namespace to "hello"
* Modifies the SBT build to fork by default so that the server is actually killed upon ctrl-c 
* Adds a mechanism to kill the server by pressing enter (sometimes doesn't work, probs asking the CE folks) 
* Inlines a mill script

### CODE REVIEW

**Comment by daddykotex** [comment]
Amazing
let me give it a shot locally and if everything works as expected I'll merge

**Comment by daddykotex** [comment]
I noticed that it asks about mill and sbt, is that expected?

Screenshot 2023-09-05 at 09 53 19

**Comment by daddykotex** [comment]
> I noticed that it asks about mill and sbt, is that expected?
> 
> Screenshot 2023-09-05 at 09 53 19

would it make sense to encode the choice as:

1. sbt = sbt == yes
2. mill = sbt == no

as an alternative to having two boolean to switch on?

**Comment by daddykotex** [comment]
```diff
commit 54c73410fb36ef69c08f829842be2b71f651fd62
Author: David Francoeur <dfrancoeur04@gmail.com>
Date:   Tue Sep 5 09:58:24 2023 -0400

    Use sbt or !sbt, no mill

diff --git a/src/main/g8/$if(mill.truthy)$.$endif$/.mill-version b/src/main/g8/$if(!sbt.truthy)$.$endif$/.mill-version
similarity index 100%
rename from src/main/g8/$if(mill.truthy)$.$endif$/.mill-version
rename to src/main/g8/$if(!sbt.truthy)$.$endif$/.mill-version
diff --git a/src/main/g8/$if(mill.truthy)$.$endif$/build.sc b/src/main/g8/$if(!sbt.truthy)$.$endif$/build.sc
similarity index 100%
rename from src/main/g8/$if(mill.truthy)$.$endif$/build.sc
rename to src/main/g8/$if(!sbt.truthy)$.$endif$/build.sc
diff --git a/src/main/g8/$if(mill.truthy)$.$endif$/mill b/src/main/g8/$if(!sbt.truthy)$.$endif$/mill
similarity index 100%
rename from src/main/g8/$if(mill.truthy)$.$endif$/mill
rename to src/main/g8/$if(!sbt.truthy)$.$endif$/mill
diff --git a/src/main/g8/default.properties b/src/main/g8/default.properties
index 1d80e73..9659fef 100644
--- a/src/main/g8/default.properties
+++ b/src/main/g8/default.properties
@@ -1,4 +1,3 @@
 name = smithy4s-quickstart
 sbt = yes
-mill = no
 smithy4s_version = maven(com.disneystreaming.smithy4s, smithy4s-core_2.13, stable)

```

this seems to work

**Comment by Baccata** [comment]
@daddykotex I was hoping there'd be some way to select values from an enumeration, but I couldn't find one. Or even a way to do conditionals that compare strings, but couldn't find one either. 

Anyway, the rationale to ask for both is that it'll give us room to add support for other build tools later (bleep being one of them). 

I think it's also better UX to be explicit about it : I think it's surprising behaviour that `sbt == no` means mill.

**Comment by daddykotex** [comment]
> I think it's also better UX to be explicit about it : I think it's surprising behaviour that sbt == no means mill.

I agree w/ that, but on the other hand, saying yes to sbt and then having to say no to mill is inconsistent

**Comment by daddykotex** [comment]
So to be clear, as we've discussed this outside of this issue:

giter8 does not allow multiple choices so it's limiting to have `sbt=yes` as sbt and `sbt=no` as mill, the current solution might be a bit counter-intuitive but will allow us to support more build tool in the future

**Pull request merged**
